First commit - mailto address on contact list added
JulietteMadi/les-cycles-du-rhone pull request #1
Opened 2022-10-06 16:30 UTC by JulietteMadi

2022-10-06 23:17 UTC, suryaambrose requested changes
Globalement c'est chouette, les quelques trucs que j'ai indiqués sont majoritairement des astuces et des conseils. 
Il n'y a qu'un seul truc sur lequel je pense qu'il faudra se repencher ensemble, c'est comment est organisé et ranger le CSS par rapport aux composants. Il y a en gros deux manières de faire et là tu mélanges un peu les deux.

1) Tu crées des classes CSS pour chaque élément de ta maquette. Chaque variation de bouton, de texte, de bloc, de logo, etc... Puis tu les utilises dans tes composants. Du coup, tes classes se situent dans un dossier styles ou équivalent, tout est importé une fois au début puis tu utilises les classes CSS par la suite. Le seul style qui reste dans les composants, c'est le positionnement. 
Ça fonctionne bien si tu as beaucoup d'éléments réutilisés
2) Tu crées une classe CSS pour chaque composant, avec tout ce dont il a besoin. C'est un peu l'opposé du précédent, et ça demande de quand même définir certaines règles pour que ce ne soit pas complètement la jungle, mais ce n'est pas inintéressant, et ça fonctionne bien mieux lorsqu'il y a beaucoup d'éléments au design très différent.

Je pense qu'il faudra qu'on se pose ensemble avec tes maquettes pour voir ça :)

2022-10-06 23:17 UTC, suryaambrose commented on src/Components/HomePage.js
> +                <h2 className='iceBreaker'>Réparation de vélos électriques et mécaniques à domicile dans le département du Rhône</h2>
iceBreaker ce n'est pas très explicite comme nom :) 
Je crois qu'il va falloir qu'on voit ensemble pour le nommage en fait. Cf mon commentaire final

2022-10-06 23:17 UTC, suryaambrose commented on src/Components/HomePage.js
> +    return(
Je pense que ça vaudrait le coup de découper un peu tout ce gros bloc en plusieurs petits composants, ça facilitera la maintenance par la suite.

2022-10-07 07:44 UTC, JulietteMadi commented on public/index.html
> +    <link rel="apple-touch-icon" href="%PUBLIC_URL%/../../src/Assets/LogoLCDR.png" />
Ok je vais commencer par la première option, on verra pour le deuxième ensemble 👍

2022-10-08 14:39 UTC, suryaambrose approved these changes

2022-10-08 14:40 UTC, suryaambrose approved these changes

2022-10-08 14:40 UTC, merged